version: '3.9'

services:
  api:
    build:
      context: przecinak
    image: przecinak_api
    ports:
      - 81:80
    volumes:
      - ./przecinak/przecinak:/app/przecinak
    command: uvicorn przecinak.api:app --host 0.0.0.0 --port 80 --reload
